---
- name: Install required packages
  hosts: wordpress
  become: yes
  tasks:
    - name: Update apt cache
      apt: update_cache=yes

    - name: Install Apache, MySQL, PHP, and required PHP modules
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apache2
        - mysql-server
        - php
        - libapache2-mod-php
        - php-mysql
        - php-gd
        - php-curl

    - name: Start and enable Apache service
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Start and enable MySQL service
      service:
        name: mysql
        state: started
        enabled: yes

- name: Install and configure WordPress
  hosts: wordpress
  become: yes
  tasks:
    - name: Download WordPress
      get_url:
        url: "https://wordpress.org/latest.tar.gz"
        dest: "/tmp/wordpress.tar.gz"

    - name: Extract WordPress archive
      unarchive:
        src: "/tmp/wordpress.tar.gz"
        dest: "/var/www/html/"
        remote_src: yes
        creates: "/var/www/html/wordpress"

    - name: Set ownership and permissions
      file:
        path: "/var/www/html/wordpress"
        owner: www-data
        group: www-data
        recurse: yes

    - name: Copy WordPress configuration file
      copy:
        src: "/var/www/html/wordpress/wp-config-sample.php"
        dest: "/var/www/html/wordpress/wp-config.php"
        owner: www-data
        group: www-data

    - name: Configure WordPress database settings
      lineinfile:
        path: "/var/www/html/wordpress/wp-config.php"
        line: "{{ item }}"
      with_items:
        - "define('DB_NAME', 'wordpress')"
        - "define('DB_USER', 'wordpress')"
        - "define('DB_PASSWORD', 'your_database_password')"
        - "define('DB_HOST', 'localhost')"

- name: Restart Apache for changes to take effect
  hosts: wordpress
  become: yes
  tasks:
    - name: Restart Apache service
      service:
        name: apache2
        state: restarted
